# Generated by Django 4.2.5 on 2023-10-09 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_drinkscategory_drinks_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drinks',
            old_name='drink_name',
            new_name='drink',
        ),
    ]
